### ISSUE TITLE
fix MSS logo on offline content

### ISSUE THREAD

**Issue by cyberorg** [RechercheTech/mss-doc#23]
It has couple of issues that need fixing

1. It does not scale like other images on that page on mobile devices.

2. White background does not go well with the page theme

**Comment by intelliant01** [comment]
@cyberorg I did consider these two points but did not bother about scale because mostly it is meant to be consumed over  a desktop screen. 

However you can use the below changes.
 
Add to templatemo-style.css -
```
@media only screen and (max-width: 360px) {
#branding img{width: 200px !important; }
}
```
and change line 39 in index.html from 
```
<div class="site-banner">
```
to
```
<div id="branding" class="site-banner">
```
and change img src to mss.svg

SVG - https://drive.google.com/open?id=0B2wpK6fFQqSjNHhna2NtT0VWX28

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/offlinewebinfra#7
